[build]
cmd = "npm install && cd frontend && npm install && npm run build && cd .."

[deploy]
startCommand = "cd backend && npm start"

[env]
NODE_ENV = "production"

[healthcheck]
path = "/api/health"
timeout = 60

[volumes]
uploads = "/app/uploads"